### PR TITLE
Padding and plot limits, extremely small step sizes

### PR DESCRIPTION
**Pull request by johnpaustian**
Fixes issue #10, replaces hard-coded padding with a percentage of step size. Adds limits to path plot to mimic density and group velocity plots. 

02density
02groupv
02raypath

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
great !!

**Comment by ThomasLecocq** [comment]
looks good and simple, please add your name to the contributors and I'll merge the PR. Thanks!

**Comment by johnpaustian** [comment]
Done, thanks Thomas!

**Comment by ThomasLecocq** [comment]
Thanks to you !!

**Pull request merged**
