### PR TITLE
Updates to FTAN routines

### PR DESCRIPTION
**Pull request by dylanmikesell**
I have fixed both ftan and iftan to work with all four of the diagramtype (PV, FV, PT, FT), as well as fixed the interpolation routine when writing TOMO_DISP files. I also moved the iftan and ftan intermediate output files (i.e. a bunch of TXT files) to their own unique folders so they stop clogging the local directory where the code is ran.

Also added the ability for the user to view the seismic trace in FTAN after applying a bandpass filter to the traces based on fmin,fmax parameters. This is a button, just like the "normalized" button to normalize the FTAN matrix columns.

### CODE REVIEW

**Comment by dylanmikesell** [comment]
Any chance we will see this pull request completed this week?

**Comment by ThomasLecocq** [comment]
I don't have much time to test it, but if you feel it works well, I'm OK to merge. We can still bugfix in case of later. So if you ✅  I'll merge now?

**Comment by dylanmikesell** [comment]
I think it is good. I will have John run tests this week with his data and
see anything strange happens.

**Comment by ThomasLecocq** [comment]
good for me then!

**Pull request merged**
